export const provinces = [
    { id: 1, name: "Dolnośląskie" },
    { id: 2, name: "Kujawsko-Pomorskie" },
    { id: 3, name: "Lubelskie" },
    { id: 4, name: "Lubuskie" },
    { id: 5, name: "Łódzkie" },
    { id: 6, name: "Małopolskie" },
    { id: 7, name: "Mazowieckie" },
    { id: 8, name: "Opolskie" },
    { id: 9, name: "Podkarpackie" },
    { id: 10, name: "Podlaskie" },
    { id: 11, name: "Pomorskie" },
    { id: 12, name: "Śląskie" },
    { id: 13, name: "Świętokrzyskie" },
    { id: 14, name: "Warmińsko-Mazurskie" },
    { id: 15, name: "Wielkopolskie" },
    { id: 16, name: "Zachodniopomorskie" },
  ];